import { CartItem, Product, ProductVariant } from "../types";
import { getCachedProduct } from "./productCache";
import { getCachedProductVariants } from "./productVariantCache";

/** Fallback när inget SKU anges i admin. */
export function defaultProductSku(productId: string): string {
  return `NH-${productId.slice(-6).toUpperCase()}`;
}

/** Hitta variant-SKU via id i produktlista eller variant-cache. */
export function variantSkuForCart(
  productId: string,
  variant?: Pick<ProductVariant, "id" | "sku"> | null
): string | undefined {
  const inline = variant?.sku?.trim();
  if (inline) return inline;
  if (!variant?.id) return undefined;

  const cached = getCachedProductVariants(productId);
  const fromCache = cached?.variants.find((v) => v.id === variant.id)?.sku?.trim();
  return fromCache || undefined;
}

/** Slå ihop variant med fullständig data (inkl. SKU) inför varukorg. */
export function resolveVariantForCart(
  productId: string,
  variant?: ProductVariant | null,
  productVariants?: ProductVariant[]
): ProductVariant | undefined {
  if (!variant) return undefined;

  const fromList = productVariants?.find((v) => v.id === variant.id);
  const cached = getCachedProductVariants(productId);
  const fromCache = cached?.variants.find((v) => v.id === variant.id);

  return {
    ...fromCache,
    ...fromList,
    ...variant,
    sku: variant.sku?.trim() || fromList?.sku?.trim() || fromCache?.sku?.trim() || undefined,
  };
}

/** Effektivt artikelnummer: variant-SKU → produkt-SKU → auto-genererat. */
export function resolveLineSku(
  product: Pick<Product, "id" | "sku">,
  variant?: Pick<ProductVariant, "id" | "sku"> | null
): string {
  const variantSku = variantSkuForCart(product.id, variant);
  if (variantSku) return variantSku;

  const productSku = product.sku?.trim();
  if (productSku) return productSku;

  return defaultProductSku(product.id);
}

export function isAutoGeneratedSku(sku: string | undefined, productId: string): boolean {
  if (!sku?.trim()) return true;
  return sku.trim() === defaultProductSku(productId);
}

/** Hämta senaste produkt-SKU från cache (shop/produktsida). */
export function productSkuForCart(productId: string, fallback?: string): string | undefined {
  const cached = getCachedProduct(productId);
  const cachedSku = cached?.sku?.trim();
  if (cachedSku) return cachedSku;
  const fallbackSku = fallback?.trim();
  return fallbackSku || undefined;
}

/** Uppdatera varukorgsrad med senaste SKU från DB-cache (ignorerar sparat SKU). */
export function enrichCartItemSkuFromDb(item: CartItem): CartItem {
  const selectedVariant = item.selectedVariant
    ? resolveVariantForCart(item.id, { ...item.selectedVariant, sku: undefined })
    : undefined;
  const cachedSku = getCachedProduct(item.id)?.sku?.trim();
  const sku = resolveLineSku({ id: item.id, sku: cachedSku }, selectedVariant);

  const variantUnchanged =
    !selectedVariant ||
    (item.selectedVariant?.id === selectedVariant.id &&
      item.selectedVariant?.sku === selectedVariant.sku);

  if (sku === item.sku && variantUnchanged) return item;

  return {
    ...item,
    sku,
    selectedVariant: selectedVariant
      ? {
          id: selectedVariant.id,
          label: selectedVariant.label,
          stock: selectedVariant.stock,
          color: selectedVariant.color,
          size: selectedVariant.size,
          weightGrams: selectedVariant.weightGrams,
          sku: selectedVariant.sku,
        }
      : item.selectedVariant,
  };
}

/** Uppdatera varukorgsrad med SKU från produkt- och variantcache. */
export function enrichCartItemSku(item: CartItem): CartItem {
  const selectedVariant = item.selectedVariant
    ? resolveVariantForCart(item.id, item.selectedVariant)
    : undefined;
  const sku = resolveLineSku(
    { id: item.id, sku: productSkuForCart(item.id, item.sku) },
    selectedVariant
  );

  const variantUnchanged =
    !selectedVariant ||
    (item.selectedVariant?.id === selectedVariant.id &&
      item.selectedVariant?.sku === selectedVariant.sku);

  if (sku === item.sku && variantUnchanged) return item;

  return {
    ...item,
    sku,
    selectedVariant: selectedVariant ?? item.selectedVariant,
  };
}

/** SKU för visning — prioriterar variant-SKU från cache. */
export function resolveCartLineSku(item: CartItem): string {
  return resolveLineSku(
    { id: item.id, sku: productSkuForCart(item.id, item.sku) },
    item.selectedVariant ? resolveVariantForCart(item.id, item.selectedVariant) : undefined
  );
}

/** Slå ihop produkt med cachad SKU innan varukorg byggs. */
export function mergeProductSkuForCart(product: Product): Product {
  const cachedSku = getCachedProduct(product.id)?.sku?.trim();
  if (!cachedSku || product.sku?.trim() === cachedSku) return product;
  return { ...product, sku: cachedSku };
}

/** Visningsformat på produktsidan. */
export function formatSkuLabel(sku: string): string {
  const trimmed = sku.trim();
  if (!trimmed) return "";
  if (/^art\.?\s*nr/i.test(trimmed)) return trimmed;
  return `Art.nr: ${trimmed}`;
}

/** SKU för vald storlek innan färg valts (kläder). */
export function resolveSkuForClothingSize(
  product: Pick<Product, "id" | "sku" | "variants">,
  size: string | null | undefined
): string | undefined {
  if (!size) return undefined;
  const match = product.variants?.find((v) => v.size === size);
  if (!match) return undefined;
  return resolveLineSku(product, match);
}
